# -*- coding: utf-8 -*-
"""OnlineDeploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2NMwabn9KkXY8Ql3lCiezsXi3L2z9nR
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.metrics.pairwise import cosine_similarity

# ---------------- LOAD FILES ----------------
df = pd.read_csv("final_df.csv", on_bad_lines='skip')

tfidf = pickle.load(open("tfidf.pkl", "rb"))
tfidf_matrix = pickle.load(open("tfidf_matrix.pkl", "rb"))
item_similarity = pickle.load(open("item_similarity.pkl", "rb"))

course_id_to_index = pickle.load(open("course_id_to_index.pkl", "rb"))
index_to_course_id = pickle.load(open("index_to_course_id.pkl", "rb"))

# ---------------- FUNCTIONS ----------------

def get_course_details(course_ids):
    return (
        df[df['course_id'].isin(course_ids)]
        [['course_id', 'course_name']]
        .drop_duplicates(subset='course_id')
    )


def recommend_hybrid_optimized(course_id, input_text, top_n=5):

    if course_id not in course_id_to_index:
        return pd.DataFrame()

    idx = course_id_to_index[course_id]

    # =========================================================
    # 🔥 CASE 1: USER ENTERS TEXT → PURE CONTENT BASED
    # =========================================================
    if input_text.strip() != "":
        input_vec = tfidf.transform([input_text])

        content_scores = cosine_similarity(
            input_vec,
            tfidf_matrix
        ).flatten()

        top_indices = np.argsort(-content_scores)[:top_n + 10]

        # ✅ FIX: use df instead of mapping
        final_course_ids = df.iloc[top_indices]['course_id'].values

        # remove selected course
        final_course_ids = [cid for cid in final_course_ids if cid != course_id]

        result = get_course_details(final_course_ids)

        return result.head(top_n)

    # =========================================================
    # 🔥 CASE 2: NO INPUT → HYBRID MODEL
    # =========================================================
    cf_scores = item_similarity[idx]

    if hasattr(cf_scores, "toarray"):
        cf_scores = cf_scores.toarray()

    cf_scores = cf_scores.flatten()

    top_k = 500
    candidate_idx = np.argsort(-cf_scores)[:top_k]

    # small content influence
    input_vec = tfidf.transform([""])
    content_scores = cosine_similarity(
        input_vec,
        tfidf_matrix[candidate_idx]
    ).flatten()

    # normalize
    cf_norm = (cf_scores[candidate_idx] - cf_scores[candidate_idx].min()) / (
        cf_scores[candidate_idx].max() - cf_scores[candidate_idx].min() + 1e-9
    )

    content_norm = (content_scores - content_scores.min()) / (
        content_scores.max() - content_scores.min() + 1e-9
    )

    hybrid_scores = 0.8 * cf_norm + 0.2 * content_norm

    top_indices = np.argsort(-hybrid_scores)[:top_n]
    final_idx = candidate_idx[top_indices]

    # ✅ FIX: use df instead of mapping
    final_course_ids = df.iloc[final_idx]['course_id'].values

    result = get_course_details(final_course_ids)

    return result.head(top_n)

# ---------------- SIDEBAR ----------------
st.sidebar.title("📌 Navigation")

page = st.sidebar.selectbox(
    "Go to",
    ["Home", "Recommendations", "Insights"]
)

# ---------------- HOME ----------------
if page == "Home":
    st.title("🎓 Online Course Recommendation System")

    st.write("""
    This application uses a **Hybrid Recommendation Model** that combines:

    ✔ Collaborative Filtering (user behavior)
    ✔ Content-Based Filtering (course features)
    """)

    st.success("🚀 Best Model Selected: Hybrid Model")

# ---------------- RECOMMENDATIONS ----------------
elif page == "Recommendations":

    st.title("🎯 Get Personalized Course Recommendations")

    course_list = df['course_name'].unique()
    selected_course = st.selectbox("📚 Select a course", course_list)

    user_input = st.text_input("🔍 Enter your interest (e.g., Python, AI, Data Science)")

    if st.button("Recommend"):
        course_id = df[df['course_name'] == selected_course]['course_id'].values[0]

        # 🔍 DEBUG
        st.write("User input:", user_input)
        st.write("TF-IDF features sample:", tfidf.get_feature_names_out()[:20])

        recommendations = recommend_hybrid_optimized(course_id, user_input)

        if recommendations.empty:
            st.warning("No recommendations found")
        else:
            st.subheader("📌 Recommended Courses")

            for _, row in recommendations.iterrows():
                st.write("👉", row['course_name'])

            st.info("💡 Recommendations generated using Hybrid Model (Optimized)")

# ---------------- INSIGHTS ----------------
elif page == "Insights":

    st.title("📊 Course Insights")

    # Dataset Overview
    st.subheader("📁 Dataset Overview")

    st.write("### 🔢 Dataset Shape")
    st.write(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

    st.write("### 📌 Column Names")
    st.write(df.columns.tolist())

    # Show Data
    st.subheader("🔍 Sample Data (First 10 Rows)")
    st.dataframe(df.head(10))

    # Top Courses
    st.subheader("🔥 Top Courses by Enrollment")
    top_courses = df.groupby('course_name')['enrollment_numbers'].sum().sort_values(ascending=False).head(10)
    st.bar_chart(top_courses)

    # Rating Distribution
    st.subheader("⭐ Rating Distribution")
    st.bar_chart(df['rating'].value_counts())

    # Price vs Rating
    st.subheader("💰 Price vs Rating")
    st.scatter_chart(df[['course_price', 'rating']])

    # Filter
    st.subheader("🎯 Filter by Difficulty")

    difficulty = st.selectbox("Select Difficulty", df['difficulty_level'].unique())

    filtered_df = df[df['difficulty_level'] == difficulty]

    st.dataframe(filtered_df.head(10))

